/**
 * Compiles webflow-pages/ into data the Designer Extension can apply.
 *
 * The extension cannot read the repo at runtime — it is served as static files
 * to an iframe inside the Designer — so the four page bodies and the whole of
 * shared.css are baked into a TypeScript module here.
 *
 * The CSS is parsed rather than passed through, because the Designer API has no
 * "apply this stylesheet" call. Styles are created one at a time with
 * `createStyle(name)` and `setProperties(props, {breakpoint, pseudo})`, so every
 * rule has to be reduced to that shape. This is only tractable because
 * shared.css was written under the constraint that every selector is a single
 * class — validate.mjs enforces it.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PAGES = join(HERE, "..", "webflow-pages");

/** Webflow's breakpoints, keyed by the max-width the stylesheet uses. */
const BREAKPOINTS = { 991: "medium", 767: "small", 479: "tiny" };

/** Splits `.a11yp_cta:hover` into its class name and pseudo state. */
function parseSelector(raw) {
  const sel = raw.trim();
  const m = /^\.([A-Za-z0-9_-]+)(?::([a-z-]+))?$/.exec(sel);
  if (!m) return null;
  return { className: m[1], pseudo: m[2] ?? null };
}

function parseDeclarations(block) {
  const props = {};
  for (const decl of block.split(";")) {
    const i = decl.indexOf(":");
    if (i === -1) continue;
    const name = decl.slice(0, i).trim();
    const value = decl.slice(i + 1).trim();
    if (!name || !value) continue;
    props[name] = value;
  }
  return props;
}

/** Returns [{className, pseudo, breakpoint, props}], one entry per rule. */
function parseCss(css) {
  const clean = css.replace(/\/\*[\s\S]*?\*\//g, "");
  const rules = [];
  const skipped = [];

  // Pull @media blocks out first so the remainder is flat.
  const mediaRe = /@media([^{]+)\{([\s\S]*?)\n\}/g;
  let rest = clean;
  let m;
  while ((m = mediaRe.exec(clean))) {
    const width = /max-width:\s*(\d+)px/.exec(m[1])?.[1];
    const breakpoint = BREAKPOINTS[Number(width)];
    if (!breakpoint) {
      skipped.push(`@media${m[1].trim()} — not a Webflow breakpoint`);
      continue;
    }
    for (const r of flatRules(m[2])) rules.push({ ...r, breakpoint });
    rest = rest.replace(m[0], "");
  }

  for (const r of flatRules(rest)) rules.push({ ...r, breakpoint: "main" });

  function* flatRules(source) {
    const ruleRe = /([^{}]+)\{([^{}]*)\}/g;
    let r;
    while ((r = ruleRe.exec(source))) {
      const props = parseDeclarations(r[2]);
      if (Object.keys(props).length === 0) continue;
      // A comma-separated selector is several rules sharing a block.
      for (const part of r[1].split(",")) {
        const parsed = parseSelector(part);
        if (!parsed) {
          skipped.push(part.trim());
          continue;
        }
        yield { ...parsed, props };
      }
    }
  }

  return { rules, skipped };
}

const css = readFileSync(join(PAGES, "shared.css"), "utf8");
const { rules, skipped } = parseCss(css);

if (skipped.length) {
  console.error("Selectors this parser cannot express as a Webflow style:");
  for (const s of skipped) console.error("  " + s);
  console.error(
    "\nEvery selector must be a single class, optionally with one pseudo state.",
  );
  process.exit(1);
}

const pages = readdirSync(PAGES)
  .filter((f) => f.endsWith(".html"))
  .map((f) => ({
    slug: `tools/${f.replace(/\.html$/, "")}`,
    file: f,
    html: readFileSync(join(PAGES, f), "utf8").trim(),
  }));

const out = `// GENERATED by generate-data.mjs — do not edit.
// Source: webflow-pages/*.html and webflow-pages/shared.css
export type StyleRule = {
  className: string;
  pseudo: string | null;
  breakpoint: string;
  props: Record<string, string>;
};
export type PageBody = { slug: string; file: string; html: string };

export const STYLE_RULES: StyleRule[] = ${JSON.stringify(rules, null, 2)};

export const PAGE_BODIES: PageBody[] = ${JSON.stringify(pages, null, 2)};
`;

writeFileSync(join(HERE, "src", "pages-data.ts"), out, "utf8");

const byBreakpoint = rules.reduce((acc, r) => {
  acc[r.breakpoint] = (acc[r.breakpoint] ?? 0) + 1;
  return acc;
}, {});
console.log(`  ${rules.length} style rules ${JSON.stringify(byBreakpoint)}`);
console.log(`  ${new Set(rules.map((r) => r.className)).size} distinct classes`);
console.log(`  ${rules.filter((r) => r.pseudo).length} with a pseudo state`);
console.log(`  ${pages.length} page bodies`);
